using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kuestencode.Werkbank.Host.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddFeedback : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS host.""FeedbackSettings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Role"" integer NOT NULL DEFAULT 0,
                    ""HubUrl"" character varying(500) NULL,
                    ""ApiKey"" character varying(1000) NULL,
                    ""LastSyncAt"" timestamp with time zone NULL,
                    ""NotifyOnNewReport"" boolean NOT NULL DEFAULT false,
                    ""NotificationEmail"" character varying(200) NULL,
                    ""MaxFileSizeMb"" integer NOT NULL DEFAULT 5,
                    ""MaxReportSizeMb"" integer NOT NULL DEFAULT 20,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE TABLE IF NOT EXISTS host.""FeedbackInstances"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" character varying(200) NOT NULL,
                    ""ApiKeyHash"" character varying(64) NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FeedbackInstances_ApiKeyHash"" ON host.""FeedbackInstances"" (""ApiKeyHash"");

                CREATE TABLE IF NOT EXISTS host.""FeedbackReports"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""InstanceId"" integer NOT NULL,
                    ""ClientReportId"" uuid NOT NULL,
                    ""Type"" integer NOT NULL,
                    ""Module"" character varying(100) NULL,
                    ""Title"" character varying(200) NOT NULL,
                    ""Expected"" text NULL,
                    ""Actual"" text NOT NULL,
                    ""ReporterName"" character varying(200) NOT NULL,
                    ""PageUrl"" character varying(1000) NOT NULL,
                    ""AppVersion"" character varying(50) NOT NULL,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""DuplicateOfId"" integer NULL,
                    ""GithubIssueUrl"" character varying(500) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ""FK_FeedbackReports_FeedbackInstances_InstanceId"" FOREIGN KEY (""InstanceId"")
                        REFERENCES host.""FeedbackInstances"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_FeedbackReports_FeedbackReports_DuplicateOfId"" FOREIGN KEY (""DuplicateOfId"")
                        REFERENCES host.""FeedbackReports"" (""Id"") ON DELETE SET NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FeedbackReports_InstanceId_ClientReportId"" ON host.""FeedbackReports"" (""InstanceId"", ""ClientReportId"");
                CREATE INDEX IF NOT EXISTS ""IX_FeedbackReports_InstanceId_UpdatedAt"" ON host.""FeedbackReports"" (""InstanceId"", ""UpdatedAt"");
                CREATE INDEX IF NOT EXISTS ""IX_FeedbackReports_DuplicateOfId"" ON host.""FeedbackReports"" (""DuplicateOfId"");

                CREATE TABLE IF NOT EXISTS host.""FeedbackComments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ReportId"" integer NOT NULL,
                    ""ClientCommentId"" uuid NULL,
                    ""Author"" integer NOT NULL,
                    ""Text"" text NOT NULL,
                    ""IsInternal"" boolean NOT NULL DEFAULT false,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""FK_FeedbackComments_FeedbackReports_ReportId"" FOREIGN KEY (""ReportId"")
                        REFERENCES host.""FeedbackReports"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FeedbackComments_ReportId_ClientCommentId"" ON host.""FeedbackComments"" (""ReportId"", ""ClientCommentId"");

                CREATE TABLE IF NOT EXISTS host.""FeedbackAttachments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ReportId"" integer NOT NULL,
                    ""FileName"" character varying(255) NOT NULL,
                    ""ContentType"" character varying(100) NOT NULL,
                    ""Size"" bigint NOT NULL,
                    ""StoragePath"" character varying(500) NOT NULL,
                    CONSTRAINT ""FK_FeedbackAttachments_FeedbackReports_ReportId"" FOREIGN KEY (""ReportId"")
                        REFERENCES host.""FeedbackReports"" (""Id"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_FeedbackAttachments_ReportId"" ON host.""FeedbackAttachments"" (""ReportId"");

                CREATE TABLE IF NOT EXISTS host.""FeedbackClientReports"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientReportId"" uuid NOT NULL,
                    ""Type"" integer NOT NULL,
                    ""Module"" character varying(100) NULL,
                    ""Title"" character varying(200) NOT NULL,
                    ""Expected"" text NULL,
                    ""Actual"" text NOT NULL,
                    ""ReporterName"" character varying(200) NOT NULL,
                    ""PageUrl"" character varying(1000) NOT NULL,
                    ""AppVersion"" character varying(50) NOT NULL,
                    ""SyncState"" integer NOT NULL DEFAULT 0,
                    ""SendAttempts"" integer NOT NULL DEFAULT 0,
                    ""NextAttemptAt"" timestamp with time zone NULL,
                    ""LastError"" character varying(1000) NULL,
                    ""HubReportId"" integer NULL,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""DuplicateOfHubId"" integer NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FeedbackClientReports_ClientReportId"" ON host.""FeedbackClientReports"" (""ClientReportId"");
                CREATE INDEX IF NOT EXISTS ""IX_FeedbackClientReports_HubReportId"" ON host.""FeedbackClientReports"" (""HubReportId"");

                CREATE TABLE IF NOT EXISTS host.""FeedbackClientComments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientReportId"" integer NOT NULL,
                    ""ClientCommentId"" uuid NULL,
                    ""HubCommentId"" integer NULL,
                    ""Author"" integer NOT NULL,
                    ""Text"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""SyncState"" integer NOT NULL DEFAULT 0,
                    ""SendAttempts"" integer NOT NULL DEFAULT 0,
                    ""NextAttemptAt"" timestamp with time zone NULL,
                    ""LastError"" character varying(1000) NULL,
                    CONSTRAINT ""FK_FeedbackClientComments_FeedbackClientReports_ClientReportId"" FOREIGN KEY (""ClientReportId"")
                        REFERENCES host.""FeedbackClientReports"" (""Id"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_FeedbackClientComments_ClientReportId"" ON host.""FeedbackClientComments"" (""ClientReportId"");

                CREATE TABLE IF NOT EXISTS host.""FeedbackClientAttachments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientReportId"" integer NOT NULL,
                    ""FileName"" character varying(255) NOT NULL,
                    ""ContentType"" character varying(100) NOT NULL,
                    ""Size"" bigint NOT NULL,
                    ""StoragePath"" character varying(500) NOT NULL,
                    CONSTRAINT ""FK_FeedbackClientAttachments_FeedbackClientReports_ClientRepor~"" FOREIGN KEY (""ClientReportId"")
                        REFERENCES host.""FeedbackClientReports"" (""Id"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_FeedbackClientAttachments_ClientReportId"" ON host.""FeedbackClientAttachments"" (""ClientReportId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS host.""FeedbackClientAttachments"";
                DROP TABLE IF EXISTS host.""FeedbackClientComments"";
                DROP TABLE IF EXISTS host.""FeedbackClientReports"";
                DROP TABLE IF EXISTS host.""FeedbackAttachments"";
                DROP TABLE IF EXISTS host.""FeedbackComments"";
                DROP TABLE IF EXISTS host.""FeedbackReports"";
                DROP TABLE IF EXISTS host.""FeedbackInstances"";
                DROP TABLE IF EXISTS host.""FeedbackSettings"";
            ");
        }
    }
}
