// <auto-generated />
using System;
using Kuestencode.Werkbank.Offerte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kuestencode.Werkbank.Offerte.Data.Migrations
{
    [DbContext(typeof(OfferteDbContext))]
    partial class OfferteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("offerte")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kuestencode.Werkbank.Offerte.Domain.Entities.Angebot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AbgelaufenAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AbgelehntAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Angebotsnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("AngenommenAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bemerkungen")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DruckAnzahl")
                        .HasColumnType("integer");

                    b.Property<string>("Einleitung")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EmailAnzahl")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EmailGesendetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailGesendetAn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Erstelldatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GedrucktAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GueltigBis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KundeId")
                        .HasColumnType("integer");

                    b.Property<string>("Referenz")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Schlusstext")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("VersendetAm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Angebotsnummer")
                        .IsUnique();

                    b.ToTable("Angebote", "offerte");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Offerte.Domain.Entities.Angebotsposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AngebotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Einzelpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Rabatt")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Steuersatz")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AngebotId");

                    b.ToTable("Angebotspositionen", "offerte");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Offerte.Domain.Entities.OfferteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAccentColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("EmailClosing")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmailGreeting")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmailLayout")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmailPrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("PdfAccentColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("PdfFooterText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PdfHeaderText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PdfLayout")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PdfPrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("PdfValidityNotice")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Settings", "offerte");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Offerte.Domain.Entities.Angebotsposition", b =>
                {
                    b.HasOne("Kuestencode.Werkbank.Offerte.Domain.Entities.Angebot", "Angebot")
                        .WithMany("Positionen")
                        .HasForeignKey("AngebotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angebot");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Offerte.Domain.Entities.Angebot", b =>
                {
                    b.Navigation("Positionen");
                });
#pragma warning restore 612, 618
        }
    }
}
