// <auto-generated />
using System;
using Kuestencode.Werkbank.Saldo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kuestencode.Werkbank.Saldo.Data.Migrations
{
    [DbContext(typeof(SaldoDbContext))]
    [Migration("20260301000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("saldo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kuestencode.Werkbank.Saldo.Domain.Entities.ExportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnzahlBuchungen")
                        .HasColumnType("integer");

                    b.Property<string>("DateiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("DateiGroesse")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ExportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExportTyp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("ZeitraumBis")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ZeitraumVon")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ExportLogs", "saldo");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Saldo.Domain.Entities.KategorieKontoMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KontoNummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Kontenrahmen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReceiptaKategorie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Kontenrahmen", "KontoNummer");

                    b.HasIndex("Kontenrahmen", "ReceiptaKategorie")
                        .IsUnique();

                    b.ToTable("KategorieKontoMappings", "saldo");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Saldo.Domain.Entities.Konto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("KontoBezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KontoNummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KontoTyp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Kontenrahmen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("UstSatz")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Kontenrahmen", "KontoNummer")
                        .IsUnique();

                    b.ToTable("Konten", "saldo");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Saldo.Domain.Entities.SaldoSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BeraterNummer")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Kontenrahmen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MandantenNummer")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("WirtschaftsjahrBeginn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SaldoSettings", "saldo");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Saldo.Domain.Entities.KategorieKontoMapping", b =>
                {
                    b.HasOne("Kuestencode.Werkbank.Saldo.Domain.Entities.Konto", "Konto")
                        .WithMany("Mappings")
                        .HasForeignKey("Kontenrahmen", "KontoNummer")
                        .HasPrincipalKey("Kontenrahmen", "KontoNummer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Konto");
                });

            modelBuilder.Entity("Kuestencode.Werkbank.Saldo.Domain.Entities.Konto", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
