// <auto-generated />
using System;
using Kuestencode.Werkbank.Contracta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kuestencode.Werkbank.Contracta.Data.Migrations
{
    [DbContext(typeof(ContractaDbContext))]
    partial class ContractaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contracta")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kuestencode.Werkbank.Contracta.Domain.Entities.Wartungsvertrag", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Bezeichnung")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int?>("CustomIntervallTage")
                    .HasColumnType("integer");

                b.Property<DateTime?>("Enddatum")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("ErstelltAm")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("GeaendertAm")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Intervall")
                    .HasColumnType("integer");

                b.Property<Guid>("KundeId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("LetzteAbrechnung")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("NaechsteAbrechnung")
                    .HasColumnType("timestamp with time zone");

                b.Property<string?>("Notizen")
                    .HasColumnType("text");

                b.Property<DateTime>("Startdatum")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<string>("Vertragsnummer")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Wartungsvertraege", "contracta");
            });

            modelBuilder.Entity("Kuestencode.Werkbank.Contracta.Domain.Entities.Vertragsposition", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Einzelpreis")
                    .HasPrecision(18, 4)
                    .HasColumnType("numeric(18,4)");

                b.Property<decimal>("Menge")
                    .HasPrecision(18, 4)
                    .HasColumnType("numeric(18,4)");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<decimal>("Steuersatz")
                    .HasPrecision(5, 2)
                    .HasColumnType("numeric(5,2)");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("WartungsvertragId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("WartungsvertragId");

                b.ToTable("Vertragspositionen", "contracta");
            });

            modelBuilder.Entity("Kuestencode.Werkbank.Contracta.Domain.Entities.Vertragsposition", b =>
            {
                b.HasOne("Kuestencode.Werkbank.Contracta.Domain.Entities.Wartungsvertrag", null)
                    .WithMany("Positionen")
                    .HasForeignKey("WartungsvertragId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Kuestencode.Werkbank.Contracta.Domain.Entities.Wartungsvertrag", b =>
            {
                b.Navigation("Positionen");
            });
#pragma warning restore 612, 618
        }
    }
}
